services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  my-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-app
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/mydb
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # command: sh -c "if [ ! -d node_modules ] || [ -z \"$(ls -A node_modules 2>/dev/null)\" ]; then echo 'install node_modules...'; npm install; fi && npm run dev"
    restart: unless-stopped

volumes:
  mongo-data: