version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo-data:
